server {
        listen 443 ssl;
        listen [::]:443 ssl;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        # Matches your auto_config.sh install path
        root /var/www/html/wordpress;
        index index.php;

        location / {
            include /etc/nginx/mime.types;
            # Better for WordPress routing
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            # Ensure the file actually exists before passing to FastCGI
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$; 
            
            # Use document_root for accuracy
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
            
            fastcgi_pass wordpress:9000;
            fastcgi_param HTTPS on;
        }

        gzip on;
    }
