services:
  mariadb:
    image: mariadb
    container_name: my_mariadb_container
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file: .env
    expose:
      - "3306"
    networks:
      - inception_frontend
    healthcheck:
      test: ["CMD", "sh", "-c", "if test -f /tmp/mariadb_ready && mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD --silent; then exit 0; else exit 1; fi"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped

  wordpress:
    image: wordpress
    container_name: my_wordpress_container
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy   #testss
    volumes:
      - wordpress_volume:/var/www/html/
    env_file: .env
    expose:
      - "9000"
    networks:
      - inception_frontend
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: my_nginx_container
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html/
    env_file: .env
    ports:
      - "443:443"
    networks:
      - inception_frontend
    restart: unless-stopped

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/redrouic/data/mariadb/
  wordpress_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/redrouic/data/wordpress

networks:
  inception_frontend:
    driver: bridge
